# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
  displayName: 'npm install'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)'
    customCommand: 'run build -- --prod --base-href /tutorial/ --deploy-url /tutorial/'
    #ng build --prod --base-href /tutorial/ --deploy-url /assets/ this will set the src path to assets
    # <link href="/assets/styles.xxxx.bundle.css" rel="styleshee...
  displayName: 'build production mode'

#- script: |
    #npm install -g @angular/cli
    #npm install
    #ng build --prod
#  displayName: 'npm install and build'

- task: CmdLine@2
  inputs:
    script: 'dir'
    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'List source directory contents'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy dist to ArtifactStagingDirectory'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'DockerFile'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy DockerFile to dist folder'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy yaml files to dist folder'

- task: CmdLine@2
  inputs:
    script: 'dir'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  displayName: 'List staging directory contents'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dist'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'