apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
      kubenetes-tutorial-name: tour-of-heroes
    name: tour-of-heroes-deployment
spec:
    replicas: 5
    template:
        metadata:
            name: why-is-this
            creationTimestamp: null
            labels:
              clskubernetes-tutorial-name: tour-of-heroes
        spec:
             containers:
                 - name: tour-of-heroes-containers
                   image: avais88786/tourofheroes:latest
                   ports:
                      - containerPort: 80