apiVersion: v1
kind: Service
metadata:
    name: tour-of-heroes-service
    labels:
        kubernetes-tutorial: tour-of-heroes-service
spec:
    #clusterIP: None
    #externalIPs:
    #    - 10.2.3.4
    type: LoadBalancer
    ports:
        - name: node-port-1
          port: 80
          #targetPort: 55555
    selector:
      kubernetes-tutorial-name: tour-of-heroes