{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tour-of-heroes-charts.serviceAccountName" . }}
  labels:
{{ include "tour-of-heroes-charts.labels" . | nindent 4 }}
{{- end -}}
